baseURL = "https://jaquesbody.github.io/know/"
languageCode = "en-gb"
title = "Know"
publishDir = "docs"

disableKinds = ["taxonomy", "term"]

[markup] [markup.goldmark] [markup.goldmark.renderer]
      unsafe = true  # required: SVG elements rendered directly in markdown content
